### ISSUE TITLE
Customize title text  (like outputTemplate)

### ISSUE THREAD

**Issue by Dana2917** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#12]
It would really help if the title text could be customized per log entry similar to the outputTemplate.  

We have a multitenant environment, and it would be great to have a title something like,
`"{Tenant} {Level} {Message}"`

It would be fine if the title was truncated, if there's a limit in Teams.  

Thanks!

**Comment by SeppPenner** [comment]
I will check this now :)

**Short update**: Currently, the title is set like this from the options globally: `Title = this.options.Title`. Now, this should be customizable like the output template. I will see, how this can be achieved without breaking the current configuration(s).

**Update 2 / question:** How do you want to handle the output template for the titles? The problem is that the `LogEvent` from Serilog internally only has the

```csharp
/// <summary>
/// The message template describing the event.
/// </summary>
public MessageTemplate MessageTemplate { get; }
```

property that is used to show the formatted text. However, there is no possibility to set the title. I'm not sure if I can extend this easily as it's maintained under https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEvent.cs. I will see if I can find a proper solution, but it can take a while.

**Comment by SeppPenner** [comment]
Might work to implement something like https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs, but more simple.

**Comment by Dana2917** [comment]
TextFormatter looks like a good idea.  :-)

Maybe simpler, could there be an option to just use the message as the title?  This would not be quite as good as completely customizing the title but would still be helpful, because you would get more information in the notification from Teams instead of just "My Title".

**Comment by SeppPenner** [comment]
I will check this feature today again, I guess, it might be possible (And even not so complicated to implement as I thought at first).

**Comment by SeppPenner** [comment]
In the next version, there will be a `titleTemplate` available instead of the `title`, check the test under: https://github.com/serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative/blob/e348412d6d38243d9f47f2eeab14438f6e951410/src/Serilog.Sinks.MicrosoftTeams.Tests/MicrosoftTeamsSinkTest.cs#L141

The only problem is that the message needs to contain the named parameter `Log.Information("My message: {Property}, {Tenant}", 1, "TestTenant1").`

--------------------------------------

So, there are 2 options as far as I know:
1. Directly add your title properties to the message: `Log.Information("My message: {Property}, {Tenant}", 1, "TestTenant1").`
2. Add the title properties within certain statements within the log context (using enrichment from https://github.com/serilog/serilog/wiki/Enrichment) --> The advantage here is that the property is available, but not shown in the message template.
```csharp
using (LogContext.PushProperty("Tenant", "TestTenant1"))
{
    Log.Information("My message");
}
```

I hope, this is what you wanted to do (At least it is the easiest way for me to not re-implement / copy the whole code from the Serilog.Formatting namespace 😅

**Comment by Dana2917** [comment]
Great, it works perfectly!  I do exactly what you have above with LogContext.PushProperty.   THANKS, this helps a lot!
