### ISSUE TITLE
OmitPropertiesSection in appsettings is ignored

### ISSUE THREAD

**Issue by martinAusBerlin** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#8]
The call from the config looks like this:

`MicrosoftTeamsSinkOptions microsoftTeamsSinkOptions = new MicrosoftTeamsSinkOptions(webHookUri, title, batchSizeLimit, period, formatProvider, LogEventLevel.Verbose, false, proxy);`

OmitPropertiesSection is always set to false when reading the config.

**Comment by SeppPenner** [comment]
I guess, this happens because the `LoggerConfigurationMicrosoftTeamsExtensions` class doesn't have a proper constructor that sets all properties yet?

https://github.com/SeppPenner/Serilog.Sinks.MicrosoftTeams/blob/71cd436876b9bd3cc1d7c7ab6fe781a563fbf323/src/Serilog.Sinks.MicrosoftTeams/LoggerConfigurationMicrosoftTeamsExtensions.cs#L54

If I change this line to:

```csharp
var microsoftTeamsSinkOptions = new MicrosoftTeamsSinkOptions(webHookUri, title, batchSizeLimit, period, formatProvider, restrictedToMinimumLevel, omitPropertiesSection, proxy);
```

it should work, I would say.

**Comment by SeppPenner** [comment]
Should be fixed with https://github.com/SeppPenner/Serilog.Sinks.MicrosoftTeams/commit/a21e47ee8f0c08993a7161f7d76f0198dc9f147a. A new nuget version will be available soon.
